### PR TITLE
Test with the lowest dependencies

### PR DESCRIPTION
**Pull request by wouterj**
We should remove WebApiTest imo, as the bundle itself is capable of 5.3.3 (afaics), so we have to test against 5.3.3 and not against 5.4.

### CODE REVIEW

**Comment by dantleech** [comment]
Do you mean not use the `web-api-extension` library?

**Comment by wouterj** [comment]
Yes

**Comment by dantleech** [comment]
Hmm, would be a shame imo as its boilerplate stuff, but not sure how much it will be maintained and if it aims to support XML also /cc @stof

**Comment by dantleech** [comment]
Rebased

**Comment by dantleech** [comment]
Fails on HHVM with Guzzle.. shall we move HHVM to allowed failures?

**Comment by dbu** [comment]
are you trying to run the built-in php webserver? hhvm does not have that. 

we could use apache/nginx or something like http://www.whitewashing.de/2015/02/01/running_hhvm_webserver.html - probably provided by the Testing component. but this is a story for another day, lets just move hhvm to allowed failures for now. maybe create an issue to adjust the hhvm setup and explain its currently not working because behat needs a running webserver.

**Pull request closed without merging**
