### PR TITLE
Upgraded to latest version of Puli

### PR DESCRIPTION
**Pull request by dantleech**
Upgraded to be compatible with the latest beta version of Puli

/cc @electricmaxxx

### CODE REVIEW

**Comment by dantleech** [comment]
@electricmaxxx I do not get any of your issues when running the behat tests locally. Check the `.travis.yml` file to ensure that you are setting up your env. correctly, i.e.

```
$ ./vendor/symfony-cmf/testing/bin/travis/<something>phpcr_odm.sh
$ ./vendor/symfony-cmf/testing/bin/server # in a separate terminal / tmux panel
$ ./vendor/bin behat
```

**Comment by ElectricMaxxx** [comment]
Could be the Last Command. I simply run phpunit.xml through a intelij run config.

**Comment by ElectricMaxxx** [comment]
... Or that behat command. Need to have a look at home.

**Comment by dantleech** [comment]
Need to fix ResourceBundle to allow re-registration of factories.

**Pull request merged**
